### ISSUE TITLE
Use of code region in portal css

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4599]
## Description of problem
If you have a bit more of CSS in your portal.css (especially common during develop stages) the UI gets cluttered. 

## Description of solution
Would be awesome to have a - to collapse (default) and a + to expand teh code region. Like Visual studio.
Ideally automatically but a convention like /* #region */ end /* #endregion */ would also do.

**Comment by valadas** [comment]
Well, this is already possible but you need your region in a css comment like so:

```css
/*#region RegionName*/
    .someclass{
        background-color: blue;
    }
/*#endregion RegionName*/
```

And then in the monaco editor it will give you a collapsing block like so:
![image](https://user-images.githubusercontent.com/6371568/113903974-8ad8f280-979f-11eb-9312-27dbb3d430c1.png)
